/* eslint-disable */
// Generated by scripts/generate-typescript-spec.mjs. Do not edit by hand.

export type Labels = string[];

export interface Taskpack {
  schema_version: "v1alpha1";
  taskpack_id: string;
  institution_id?: string;
  parent_taskpack_id?: string;
  title: string;
  objective: string;
  problem_statement?: string;
  task_type: "analysis" | "implementation" | "review" | "research" | "triage" | "evaluation" | "operations" | "custom";
  priority: "low" | "medium" | "high" | "critical";
  requested_by: ActorRef;
  role_hint?: "dri" | "explorer" | "builder" | "skeptic" | "reviewer" | "specialist" | "approver";
  inputs?: ArtifactRef[];
  references?: string[];
  labels?: Labels;
  context_budget: {
    max_input_tokens: number;
    max_output_tokens: number;
    context_strategy: "artifact_refs_first" | "summary_plus_refs" | "full_bundle";
    max_artifacts_inline?: number;
  };
  constraints?: {
    must_not?: string[];
    must_include?: string[];
    deadline_at?: string;
    cost_ceiling_usd?: number;
    tool_allowlist?: string[];
  };
  permissions: {
    allow_network: boolean;
    allow_shell: boolean;
    allow_external_write: boolean;
    approval_mode: "none" | "ask" | "required";
    scopes?: string[];
  };
  /**
   * @minItems 1
   */
  acceptance_criteria: [
    {
      criterion_id: string;
      description: string;
      required?: boolean;
      verification_hint?: string;
    },
    ...{
      criterion_id: string;
      description: string;
      required?: boolean;
      verification_hint?: string;
    }[]
  ];
  delegation_policy?: {
    allow_subtasks?: boolean;
    max_depth?: number;
    max_parallel_subtasks?: number;
  };
  created_at: string;
  trace_id?: string;
}
export interface ActorRef {
  actor_id: string;
  actor_type: "agent" | "human" | "service";
  display_name: string;
  orchestrator?: string;
  model?: string;
  endpoint?: string;
}
export interface ArtifactRef {
  artifact_id: string;
  kind: string;
  uri: string;
  version?: number;
}

export interface DriBinding {
  schema_version: "v1alpha1";
  dri_binding_id: string;
  taskpack_id: string;
  owner: ActorRef;
  reviewers?: ActorRef[];
  specialists?: ActorRef[];
  approvers?: ActorRef[];
  escalation_policy?: {
    mode?: "manual" | "time_based" | "policy_based";
    escalate_after_seconds?: number;
    targets?: ActorRef[];
  };
  approval_policy?: {
    required_for?: ("external_write" | "network" | "prod_access" | "cost_overrun" | "publication")[];
    min_approvals?: number;
  };
  visibility_policy?: {
    mode?: "team" | "project" | "institution" | "restricted";
    readers?: ActorRef[];
  };
  status: "assigned" | "accepted" | "in_progress" | "blocked" | "completed" | "canceled";
  created_at: string;
}

export interface Artifact {
  schema_version: "v1alpha1";
  artifact_id: string;
  taskpack_id: string;
  parent_artifact_ids?: string[];
  kind:
    | "report"
    | "code_patch"
    | "review"
    | "plan"
    | "dataset"
    | "decision_log"
    | "benchmark_result"
    | "skill_candidate"
    | "custom";
  title: string;
  summary?: string;
  producer: ActorRef;
  storage: {
    uri: string;
    mime_type: string;
    sha256?: string;
    size_bytes?: number;
  };
  lineage?: {
    trace_id?: string;
    run_id?: string;
    source_taskpack_ids?: string[];
  };
  evaluation_state?: {
    status?: "not_evaluated" | "pending" | "passed" | "failed";
    score?: number;
    benchmark_suite?: string;
  };
  labels?: Labels;
  security_classification?: "public" | "internal" | "restricted";
  version: number;
  created_at: string;
}

export interface PromotionRecord {
  schema_version: "v1alpha1";
  promotion_record_id: string;
  institution_id: string;
  candidate_kind: "skill" | "rule" | "prompt_pattern" | "workflow_pattern" | "review_heuristic";
  candidate_ref: ArtifactRef;
  source_run_ids?: string[];
  benchmark_suite?: string;
  metrics?: MetricDelta[];
  decision: "accepted" | "rejected" | "needs_human_review" | "deferred";
  decision_reason?: string;
  deciders?: ActorRef[];
  accepted_scope?: "institution" | "team" | "project" | "role_specific";
  decided_at: string;
}
export interface MetricDelta {
  name: string;
  before: number;
  after: number;
  direction: "higher_is_better" | "lower_is_better";
  unit?: string;
}

export interface ReplayBundle {
  schema_version: "v1alpha1";
  root_taskpack_id?: string;
  taskpack: Taskpack;
  taskpacks?: Taskpack[];
  dri_bindings: DRIBinding[];
  artifacts: Artifact[];
  promotion_records: PromotionRecord[];
}
export interface DRIBinding {
  schema_version: "v1alpha1";
  dri_binding_id: string;
  taskpack_id: string;
  owner: ActorRef;
  reviewers?: ActorRef[];
  specialists?: ActorRef[];
  approvers?: ActorRef[];
  escalation_policy?: {
    mode?: "manual" | "time_based" | "policy_based";
    escalate_after_seconds?: number;
    targets?: ActorRef[];
  };
  approval_policy?: {
    required_for?: ("external_write" | "network" | "prod_access" | "cost_overrun" | "publication")[];
    min_approvals?: number;
  };
  visibility_policy?: {
    mode?: "team" | "project" | "institution" | "restricted";
    readers?: ActorRef[];
  };
  status: "assigned" | "accepted" | "in_progress" | "blocked" | "completed" | "canceled";
  created_at: string;
}
